### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by OlegKostin** [wizered67/ProjectVisualNovel#1]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: File not found: Animations\Edgeworth.pack (Internal)
There isnt any package with such name. Can you me help plz?

**Comment by wizered67** [comment]
Hi OlegKostin! I really appreciate your interest! Everything is very much a work in progress right now and I didn't expect anyone to find or want to try this yet. I have intentionally not provided all of the assets (and I just removed more I didn't intend to include) because they are not mine and were just for testing. Edgeworth.pack is a file made with the LibGDX TexturePacker. If you want to try the project you should make your own texture atlas for a set of animations and update LoadingScreen.java to load it and not any of the old resources. Thanks again for your interest!

**Comment by wizered67** [comment]
I have re-added that missing file for now, although I should reiterate that it's only a test image and I don't own the rights to it. There may be some other missing files, so check the LoadingScreen and remove any files you don't have, or add your own. If you do end up messing around with this project, let me know what you think! Everything is still in progress so lots more is being added or changed.
